services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: on-failure

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: on-failure
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  postgres-data: